carro/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('carro.views', 
            url(r'addcarro/', 'cad_carro', ),
            url(r'getcarros/', 'get_carros', ),
            url(r'getmotores/', 'get_motores', ),
            url(r'getpastilhas/', 'get_pastilhas', ),
            url(r'^meus_carros/$','meus_carros',),
            url(r'^troca_pecas/(?P<carro_id>\d+)/$','troca_pecas', ),
			url(r'^carro/(?P<carro_id>\d+)/$','carrousuario', name='carrousuario'),
            )

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib.auth.views import login, logout

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^LavPython/', include('LavPython.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    (r'^$','views.home',),
    (r'^contato/$','contato.views.contato',),
    (r'^usuario/', include('usuario.urls')),
	(r'^trajeto/', include('trajeto.urls')),
	(r'^carro/', include('carro.urls')),
    (r'^entrar/$','views.login', ),
    (r'^sair/$',logout,{'template_name': 'sair.html'}, 'sair'),
    (r'^media/(.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    (r'^dia/',include('dia.urls')),
	(r'^historico/',include('historico.urls')),
)

carro/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

COMBUSTIVEIS = (
	('A','Alcool'),
	('G','Gasolina'),
	('D','Diesel'),
	('N','Gas Natural'),
	)


class Marca(models.Model):
	nome = models.CharField(max_length = 255)
	
	def __unicode__(self):
		return self.nome

class Carro(models.Model):
	marca = models.ForeignKey('Marca',)
	modelo = models.CharField(max_length = 255)
#	motor = models.ForeignKey('Motor')
#	partilhaFreio = models.ForeignKey('PastilhaFreio')

	def __unicode__(self):
		return self.modelo

class Fabricante(models.Model):
	nome = models.CharField(max_length = 255)
	
	def __unicode__(self):
		return self.nome
		
class Peca(models.Model):
	class Meta:
		abstract = True

	modelo = models.CharField(max_length = 255)
	fabricante = models.ForeignKey('Fabricante')
	carros = models.ManyToManyField(Carro,blank=True,null=True)
	kmMax = models.DecimalField(max_digits = 10,decimal_places = 2)

	def __unicode__(self):
		return self.modelo

class Motor(Peca,models.Model):
	cilindros = models.DecimalField(max_digits = 2, decimal_places = 0)
	combustivel = models.CharField(choices = COMBUSTIVEIS, max_length = 30)
	potencia = models.DecimalField(max_digits = 4, decimal_places = 0)
	kmLitro = models.DecimalField(max_digits = 3,decimal_places = 0)
	

class PastilhaFreio(Peca, models.Model):
	cod_fabricante = models.DecimalField(max_digits = 10, decimal_places= 0)

class CarroUsuario(models.Model):
	usuario = models.ForeignKey(User)
	carro = models.ForeignKey(Carro)

	motor = models.ForeignKey(Motor)
	kmMotor = models.DecimalField(max_digits = 10,decimal_places = 2,default=0,verbose_name="Km do motor",help_text="Quilometragem rodada utilizando esse motor")

	pastilhaFreio = models.ForeignKey(PastilhaFreio)
	kmPastilha = models.DecimalField(max_digits = 10,decimal_places=2,default=0,verbose_name="Km da pastilha",help_text="Quilometragem rodada utilizando essa pastilha")

	quilometragem = models.DecimalField(max_digits = 10,decimal_places=2,default=0)
	ultimoUpdate = models.DateField()

	def __unicode__(self):
		return self.carro.modelo
	   
	def get_absolute_url(self):
		return reverse('carrousuario', kwargs={'carro_id': self.id})

carro/forms.py
from django.contrib.auth.forms import User
from django import forms
from forms import *
from models import *
from datetime import date

class FormTrocaPeca(forms.ModelForm):
	class Meta:
		model = CarroUsuario
		exclude = ('usuario',
			   'ultimoUpdate',
			   'carro',
			   'quilometragem',
			   'kmMotor',
			   'kmPastilha'
			   )
		
	trocar_motor = forms.BooleanField(required=False,initial=False,)
	trocar_pastilhaFreio = forms.BooleanField(required=False,initial=False,)
		
	def save(self,commit=True):
		carroUsuario = super(FormTrocaPeca,self).save(commit=False)
		if self.cleaned_data['trocar_motor']:
			carroUsuario.kmMotor = 0
		if self.cleaned_data['trocar_pastilhaFreio']: 
			carroUsuario.kmPastilha = 0
		carroUsuario.save()
		


class FormCarroUsuario(forms.ModelForm):
	class Meta:
		model = CarroUsuario
		exclude = ('usuario','ultimoUpdate')
	
	marca = forms.ModelChoiceField(Marca.objects.all(), widget=forms.Select(), required=True)
	
	def __init__(self, *args, **kwargs):
		self.base_fields['carro'].choices = ""
		self.base_fields['motor'].choices = ""
		self.base_fields['pastilhaFreio'].choices = ""
		super(FormCarroUsuario, self).__init__(*args,**kwargs)
	
	"""Passando-se o ultimoUpdate através da view. Com isso, fica mais fácil fazer demonstrações, embora o default seja passar como argumento na view date.today()""" 
	def save(self, usuario,ultimoUpdate=date.today(),commit=True):
		carroUsuario = super(FormCarroUsuario, self).save(commit=False)
		
		carroUsuario.usuario = usuario
		carroUsuario.ultimoUpdate = ultimoUpdate
		
		if commit:
			carroUsuario.save()
        
		return carroUsuario

carro/views.py
from django.core import serializers
from django.shortcuts import render_to_response
from models import *
from django.contrib.auth.decorators import login_required
from forms import *
from django.template import RequestContext
from django.http import HttpResponseRedirect, Http404, HttpResponse
from historico.functions import atualiza_historico_troca


@login_required
def carrousuario(request, carro_id):
	carrousuario = CarroUsuario.objects.get(id=carro_id)
	carro = Carro.objects.get(id=carrousuario.carro_id)
	motor = Motor.objects.get(id=carrousuario.motor_id)
	pastilha = PastilhaFreio.objects.get(id=carrousuario.pastilhaFreio_id)
	saude_motor =  (motor.kmMax - carrousuario.kmMotor) * 100 / motor.kmMax
	saude_pastilha = (pastilha.kmMax - carrousuario.kmPastilha) * 100 / pastilha.kmMax
	
	return render_to_response(
		'carro.html',
		locals(),
		context_instance = RequestContext(request))


@login_required
def troca_pecas(request,carro_id):
	carro = CarroUsuario.objects.get(id=carro_id)
	motor = Motor.objects.get(id=carro.motor_id)
	pastilha = PastilhaFreio.objects.get(id=carro.pastilhaFreio_id)
	
	
	saude_motor =  (motor.kmMax - carro.kmMotor) * 100 / motor.kmMax
	saude_pastilha = (pastilha.kmMax - carro.kmPastilha) * 100 / pastilha.kmMax

	if request.method == 'POST':
		form = FormTrocaPeca(request.POST, instance=carro)
		if form.is_valid():
			atualiza_historico_troca(form,carro_id)
			carro_editado = form.save()
			return HttpResponseRedirect('/')
	else:
		form = FormTrocaPeca(instance=carro)
		
	return render_to_response(
		'troca_pecas.html',
		locals(),
		context_instance = RequestContext(request))
	



@login_required
def meus_carros(request):
	carros = CarroUsuario.objects.filter(usuario=request.user)
	return render_to_response('meus_carros.html',locals(),context_instance = RequestContext(request))


@login_required
def cad_carro(request):

	if request.method == 'POST':
		form = FormCarroUsuario(request.POST)
		if form.is_valid():
			"Pode ser passado qualquer data. Essa é today eh o default"
			novo_carro = form.save(request.user)
			return HttpResponseRedirect('/')
	else:
		form = FormCarroUsuario()
        
	return render_to_response(
                            'addcarro.html',
                            locals(),
                            context_instance=RequestContext(request),
                            )

@login_required
def get_carros(request):

	id_marca = request.GET.get('id_marca', '')
	carros = Carro.objects.filter(marca = int(id_marca))
	retorno = serializers.serialize("json",  carros)
	return HttpResponse(retorno, mimetype="text/javascript")
	
@login_required
def get_motores(request):
	id_carro = request.GET.get('id_carro', '')
	motores = Carro.objects.get(id = int(id_carro)).motor_set.all()
	retorno = serializers.serialize("json", motores)
	return HttpResponse(retorno, mimetype="text/javascript")
	
@login_required
def get_pastilhas(request):
	id_carro = request.GET.get('id_carro', '')
	carro = Carro.objects.get(id = int(id_carro))
	pastilhas = Carro.objects.get(id = int(id_carro)).pastilhafreio_set.all()
	retorno = serializers.serialize("json", pastilhas)
	return HttpResponse(retorno, mimetype="text/javascript")

carro/templates/addcarro.html
{% extends "base.html" %}

{% block titulo %}
	Adicionar Carro - {{ block.super }}
{% endblock %}

{% block scripts %}
	{{ block.super }}
	<script type="text/javascript">
		$(document).ready(function()
		{
			$("#id_marca").change(function()
			{
				$.ajax(
				{
					type: "GET",
					url: '/carro/getcarros?id_marca='+$("#id_marca").val(),
					dataType: "json",
					success: function(retorno)
					{
						$("#id_carro").children().remove();
						$("#id_carro").append(
							'<option value="">---------</option>'
						);
						$.each(retorno, function(i, carro)
						{
							$("#id_carro").append(
								'<option value="'+
								carro.pk +
								'">'+
								carro.fields['modelo']+
								'</option>'
							);

						});
					}
				});
			});
			$("#id_carro").change(function()
			{
				$.ajax(
				{
					type: "GET",
					url: '/carro/getmotores?id_carro='+$("#id_carro").val(),
					dataType: "json",
					success: function(retorno)
					{
						$("#id_motor").children().remove();
						$("#id_motor").append(
							'<option value="">---------</option>'
						);
						$.each(retorno, function(i, carro)
						{
							$("#id_motor").append(
								'<option value="'+
								carro.pk +
								'">'+
								carro.fields['modelo']+
								'</option>'
							);

						});
					}
				});
			});
			$("#id_carro").change(function()
			{
				$.ajax(
				{
					type: "GET",
					url: '/carro/getpastilhas?id_carro='+$("#id_carro").val(),
					dataType: "json",
					success: function(retorno)
					{
						$("#id_pastilhaFreio").children().remove();
						$("#id_pastilhaFreio").append(
							'<option value="">---------</option>'
						);
						$.each(retorno, function(i, carro)
						{
							$("#id_pastilhaFreio").append(
								'<option value="'+
								carro.pk +
								'">'+
								carro.fields['modelo']+
								'</option>');
						});
					}
				});
			});
		});

	</script>
{% endblock %}

{% block h1 %}Adicionar Carro{% endblock %}

{% block conteudo %}
	{{ block.super }}
	<form method="post">
		{% csrf_token %}
		<table class="form">
			{{ form }}
			<tr>
				<th>&nbsp;</th>
					<td>
						<input type="submit" value="Registrar"/>
					</td>
			</tr>
		</table>
	</form>
{% endblock conteudo %}

carro/templates/carro.html
{% extends "base.html" %}

{% block titulo %}Meu Carro -- {{ block.super }}{% endblock %}

{% block h1 %}Meu Carro{% endblock %}

{% block conteudo %}
	<div id="meu_carro">
		<p><b>Modelo:</b> {{ carro.modelo }} <b>Quilometragem do Carro:</b> {{ carrousuario.quilometragem }}</p>
		<p><b>Motor:</b> {{ motor.modelo }} <b>Saúde da Peça:</b> {{ saude_motor }}</p>
		<p><b>Pastilha:</b> {{ pastilha.modelo }} <b>Saúde da Peça:</b> {{ saude_pastilha }}</p>
		<p>
			<input type=button value="Trocar Peças" onClick="parent.location='{% url carro.views.troca_pecas carro_id=carro_id %}'" />
			<input type=button value="Associar a Trajeto" onClick="parent.location='{% url dia.views.associar carro_id=carro_id %}'" />		
		</p>
	</div>
{% endblock %}

carro/templates/meus_carros.html
{% extends "base.html" %}

{% block titulo %}Meus Carros -- {{ block.super }}{% endblock %}

{% block h1 %}Meus Carros{% endblock %}
{% block conteudo %}
	<div id="meus_carros">
		{% for meu_carro in carros %}
			<div class="meu_carro">
				<a href="{{ meu_carro.get_absolute_url }}">{{ meu_carro.carro.modelo }}</a>
				-----
				<input type=button value="Trocar Peças" onClick="parent.location='{% url carro.views.troca_pecas carro_id=meu_carro.pk %}'" />
				-----
				<input type=button value="Associar a Trajeto" onClick="parent.location='{% url dia.views.associar carro_id=meu_carro.pk %}'" />
				-----
				<input type=button value="Trajetos Associados" onClick="parent.location='{% url dia.views.meus_dias carro_id=meu_carro.pk %}'" />
			</div>
		{% endfor %}
		<input type=button value="Adicionar Novo Carro" onClick="parent.location='{% url carro.views.cad_carro %}'" />
	</div>
{% endblock %}

carro/templates/troca_pecas.html
{% extends "base.html" %}

{% block titulo %}
  Troca de Peças - {{ block.super }}
{% endblock %} 

{{% block h1 %}Troca de Peças{% endblock %}

{% block conteudo %}
  {{ block.super }}
 
  <form method="post">
    {% csrf_token %}
		<table class="form">
			<tr>
				<td>
					Motor: {{ motor.modelo }} -- {{ motor.fabricante}} --  Saude:{{ saude_motor }}%  -- {{ form.motor }} -- Trocar peça? {{ form.trocar_motor }}
				</td>
			</tr>
			<tr>
				<td>
				Pastilha: {{ pastilha.modelo }} -- {{ pastilha.fabricante }} -- Saude: {{ saude_pastilha }}% -- {{ form.pastilhaFreio }} -- Trocar peça? {{ form.trocar_pastilhaFreio }}
				</td>
			</tr>
			<tr>
				<td>
				  <input type="submit" value="Modificar"/>
				</td>
			</tr>
		</table>
  </form>
{% endblock conteudo %}
  